plugins:
  - jekyll-redirect-from
  - jekyll-remote-theme

remote_theme:         andrewgjohnson/open-source-documentation-jekyll-theme
title:                imageblendedcolorallocate
name:                 imageblendedcolorallocate
description:          imageblendedcolorallocate is a function that will allocate a new blended color based on two existing allocated colors for your PHP GD images.
author:               Andrew G. Johnson
author_email:         andrew@andrewgjohnson.com
email:                andrew@andrewgjohnson.com
url:                  https://imageblendedcolorallocate.agjgd.org
includes_dir:         .
favicon:              https://github.githubassets.com/favicon.ico
footer_text:          agjgd.org
footer_url:           https://agjgd.org
copyright_year_start: 2018
syntax_highlighting:  true
cover_image:          mountains
custom_head:          <script>if (location.pathname == "/documentation" || location.pathname.indexOf("/documentation/") === 0) window.location.href = "/";</script>
social_links:
  - platform:         twitter
    url:              https://twitter.com/agjgdphp
    label:            imageblendedcolorallocate on Twitter
  - platform:         github
    url:              https://github.com/andrewgjohnson/imageblendedcolorallocate
    label:            imageblendedcolorallocate on GitHub
  - platform:         packagist
    url:              https://packagist.org/packages/andrewgjohnson/imageblendedcolorallocate
    label:            imageblendedcolorallocate on Packagist
  - platform:         patreon
    url:              https://www.patreon.com/agjopensource
    label:            imageblendedcolorallocate on Patreon
  - platform:         x
    url:              https://x.com/agjgdphp
    label:            imageblendedcolorallocate on 𝕏
exclude:              [
                       .github,
                       .github/*.md,
                       .github/*.yml,
                       .github/CODEOWNERS,
                       .github/ISSUE_TEMPLATE,
                       .github/ISSUE_TEMPLATE/*.yml,
                       CHANGELOG.md,
                       CNAME,
                       composer.json,
                       composer.lock,
                       documentation/README.md,
                       examples/*.php,
                       examples/*.ttf,
                       LICENSE,
                       README.md,
                       source,
                       vendor,
                       vendor/*.md,
                       phpcs.xml.dist,
                       tests,
                       phpunit.xml.dist
                      ]
